spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa

# Logging
logging:
  level:
    org:
      springframework:
        jdbc: debug

      hibernate:
        SQL: debug # 하이버네이트가 생성하고 실행하는 SQL을 확인할 수 있다.
        type:
          descriptor:
            sql:
              BasicBinder: trace # SQL에 바인딩 되는 파라미터를 확인할 수 있다.
    hello:
      itemservice:
        repository:
          mybatis: trace

# MyBatis
mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true

